---
title: "Visu_3div"
author: "Antonin_Colajanni"
date: "04/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Functions to reshape data
```{r functions}
library(ggplot2)
library(reshape2)
library(scales)

#' Extract one feature from the df list 
#'
#' @param data list of dataframes 
#' @param feature name of one column of the dataframes
#'
#' @return list of vector for each dataframe of the original list
extract_features_from_list <- function(data,feature = "dist"){
  return(lapply(data, "[", , feature)) }


#' Creates a dataframe with 2 columns (variable and value) from a list of vector
#'
#' @param data list of vector
#'
#' @return DataFrame
list_to_2colDF <- function(data){
  df = data.frame(do.call(cbind, data))
  return (melt(df))
}

contact_distrib <- function(interact, title){
  ggplot(data=interact, aes(x=reorder(variable, -value), y=value)) +
    geom_bar(stat="identity")+
    geom_text(aes(label=value), color="white",hjust=-0.1 , size=3.8, angle=-90) +
    scale_y_continuous(
      #breaks = c(0,100000,300000), 
      labels = comma
      ) +
    labs(title=title,
       x = "Cell line", y="Contact number")+
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90))
}


hist_contact <- function(distances, title){
  ggplot(data = distances) +
    geom_histogram(aes(x = value), bins = 30 )+
    labs(title=title) +
    facet_wrap(~ variable)
}
```



# Load data
```{r Import}
####### Filtered at pvalue = 0.05
load("/shared/ifbstor1/home/acolajanni/data/phic/rdata/3div_0.05.Rdata")
result_0.05 = extract_features_from_list(File_list_filtered0.05,"dist")
rm(File_list_filtered0.05)

####### Filtered at pvalue = 0.001
load("/shared/ifbstor1/home/acolajanni/data/phic/rdata/3div_0.001.Rdata")
result_0.001 = extract_features_from_list(File_list_filtered0.001,"dist")
rm(File_list_filtered0.001)

####### not Filtered
load("/shared/ifbstor1/home/acolajanni/data/phic/rdata/3div_po_txt.Rdata")
result_tot = extract_features_from_list(File_list,"dist")
rm(File_list)

```

# Prepare data
```{r prep}
####### Filtered at pvalue = 0.05
# distance dataframe
distances_0.05 = list_to_2colDF(result_0.05)

# Number of contact dataframe 
interact_0.05 = lapply(result_0.05,length)
interact_0.05 = list_to_2colDF(interact_0.05)


####### Filtered at pvalue = 0.001
# distance dataframe
distances_0.001 = list_to_2colDF(result_0.001)

# Number of contact dataframe 
interact_0.001 = lapply(result_0.001,length)
interact_0.001 = list_to_2colDF(interact_0.001)


####### not Filtered
# distance dataframe
distances = list_to_2colDF(result_tot)

# Number of contact dataframe 
interact = lapply(result_tot,length)
interact = list_to_2colDF(interact)

```

# Visualisation
## No filter
```{r viz1}

hist_contact(distances, title = "Distribution of contact distances of the cell lines from 3div database (PCHi-C)")
``` 


```{r viz2}

contact_distrib(interact, title = "Number of contact of the cell lines from 3div database (PCHi-C)")

``` 


## Filter at p = 0.05 / -log10(p) = 1.301
```{r viz3}

hist_contact(distances_0.05, title = "Distribution of contact distances of the cell lines from 3div database (PCHi-C filtered at p < 0.05)")
``` 


```{r viz4}

contact_distrib(interact_0.05, title = "Number of contact of the cell lines from 3div database (PCHi-C filtered at p < 0.05)")

``` 


## Filter at p = 0.001 / -log10(p) = 3
```{r viz5}

hist_contact(distances_0.001, title = "Distribution of contact distances of the cell lines from 3div database (PCHi-C filtered at p < 0.001)")
``` 


```{r viz6}

contact_distrib(interact_0.001, title = "Number of contact of the cell lines from 3div database (PCHi-C filtered at p < 0.001)")

``` 